services:
  # Backend API Service
  - type: web
    name: part-matching-engine
    env: python
    buildCommand: |
      cd backend && pip install -r requirements.txt
      mkdir -p /data/source
      cp -r ../Data/* /data/source/ || true
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    # Ensure Data directory is mounted properly
    disk:
      name: data
      mountPath: /data
      sizeGB: 1