services:
  # Backend API Service
  - type: web
    name: part-matching-engine-api
    env: python
    buildCommand: |
      cd backend && pip install -r requirements.txt
      mkdir -p /data/source
      mkdir -p /data/chroma_db
      cp -r ./Data/* /data/source/ || true
      echo "Files copied to persistent storage"
      cd /data/source && ls -la
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    # Ensure Data directory is mounted properly
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
    
  # Frontend Static Site
  - type: web
    name: part-matching-engine-frontend
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./frontend
    envVars:
      - key: API_URL
        fromService:
          name: part-matching-engine-api
          type: web
          property: url